version: "3.9"
services:

    pam-budget-service:
        build: ./api
        container_name: pam-budget-service
        hostname: pam-budget-service
        privileged: true
        depends_on:
          - db
        restart: always
        ports:
            - 23154:8080
    db:
        image: 'postgres:13.1-alpine'
        container_name: db
        environment:
        - POSTGRES_USER=compose-postgres
        - POSTGRES_PASSWORD=compose-postgres