version: "3.9"
services:
    budget-service-application:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - SUSPENDED_BOOT=n
                - DEBUG_PORT=5006
        hostname: pam-budget-service
        privileged: true
        restart: unless-stopped
        ports:
            - "23154:8080" # Default application port
            - "5006:5006" # Debug port
        environment:
            - "SPRING_PROFILES_ACTIVE=local"
        healthcheck:
            test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
            interval: 20s
            timeout: 5s
            retries: 5
            start_period: 40s